 SELECT A.ID AS ID,A.SOC AS SOC,A.FRACSEC AS FRACSEC,(B.SYSTEM_TIME - A.SYSTEM_TIME) AS ProcessingTime 
 FROM 
 (SELECT CHECK_POINT,ID,SOC,FRACSEC,CAST(SYSTEM_TIME AS INT) AS SYSTEM_TIME FROM LOG_TIME_INFO WHERE CAST(CHECK_POINT AS INT) = 1) AS A,
 (SELECT ID,CHECK_POINT,SOC,FRACSEC,MAX(CAST(SYSTEM_TIME AS INT)) AS SYSTEM_TIME 
 	FROM LOG_TIME_INFO WHERE CAST(CHECK_POINT AS INT) = 2 
 	GROUP BY CAST(SOC AS INT),CAST(FRACSEC AS INT)) AS B 
 WHERE A.SOC = B.SOC AND A.FRACSEC = B.FRACSEC;
