#!/bin/bash
START=$(date +%s.%N)
# do something
# start your script work here
#./DBServer
mysql -uroot -proot iPDC < "cfgQuery.txt"
# your logic ends here
END=$(date +%s.%N)
DIFF=$(echo "$END - $START" | bc)
echo "It took $DIFF seconds"

